### ISSUE TITLE
Token generation

### ISSUE THREAD

**Issue by javlonfattoev** [ilmhub-uz/school-management-system#26]
JWT token yasashda userni rollarini ham claimga qoshib yasashi kerak

**Comment by fuga02** [comment]
user clasini ichida role clasidan foydalanilmaganku

**Comment by Shoxrux3689** [comment]
sila aralashmi qoyurila ozim togirlab qoyaman rolini

**Comment by JamolMeyliyev** [comment]
Hop oʻzizdan qolar gap yoʻq
